apiVersion: apps/v1
kind: Deployment
metadata:
  name: shopping-guide-api
  labels:
    app: shopping-guide-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: shopping-guide-api
  template:
    metadata:
      labels:
        app: shopping-guide-api
    spec:
      containers:
      - name: api
        image: shopping-guide-api:latest
        ports:
        - containerPort: 8080
        env:
        - name: ENV
          value: "production"
        - name: REDIS_ADDR
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: redis_addr
        - name: MYSQL_DSN
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: mysql_dsn
        resources:
          requests:
            cpu: 500m
            memory: 512Mi
          limits:
            cpu: 1000m
            memory: 1Gi
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: shopping-guide-api-service
spec:
  selector:
    app: shopping-guide-api
  ports:
  - port: 80
    targetPort: 8080
  type: LoadBalancer

