# 开发环境配置
server:
  mode: debug
  
log:
  level: debug
  format: console
  output: stdout

redis:
  addr: "localhost:6380"
  password: "redis123"

mysql:
  host: localhost
  port: 3307
  user: root
  password: "mysql123"
  database: shopping_guide
  charset: utf8mb4
  parse_time: true
  loc: Local
  max_idle_conns: 10

middleware:
  cors:
    allow_origins:
      - "http://localhost:3000"
      - "http://localhost:8080"
  rate_limit:
    enabled: false
  auth:
    enabled: false

