# 默认配置
server:
  port: 8080
  mode: debug # debug/release
  read_timeout: 60s
  write_timeout: 60s
  
dify:
  base_url: "https://dify.baidu-int.com/api"
  api_key: "" # 通过环境变量 DIFY_API_KEY 设置
  timeout: 30s
  
  workflows:
    planner:
      app_id: "" # Planner工作流的App ID
      timeout: 10s
      
    executors:
      product_recommendation:
        app_id: "" # 商品推荐Executor的App ID
        timeout: 15s
        
      shopping_guide:
        app_id: "" # 售前导购Executor的App ID
        timeout: 15s
        
      qa_assistant:
        app_id: "" # 答疑助手Executor的App ID
        timeout: 15s

redis:
  addr: "localhost:6380"
  password: "redis123"
  db: 0
  pool_size: 10
  min_idle_conns: 5
  max_retries: 3
  
  # 过期时间配置
  session_ttl: 168h # 7天
  cache_ttl: 1h
  rate_limit_window: 60s

mysql:
  host: localhost
  port: 3307
  user: root
  password: "mysql123"
  database: shopping_guide
  charset: utf8mb4
  parse_time: true
  loc: Local
  max_idle_conns: 10
  max_open_conns: 100
  conn_max_lifetime: 1h

log:
  level: info # debug/info/warn/error
  format: json # json/console
  output: stdout # stdout/stderr/file
  file_path: logs/app.log
  max_size: 100 # MB
  max_backups: 10
  max_age: 30 # days
  compress: true

middleware:
  # 跨域配置
  cors:
    allow_origins:
      - "*"
    allow_methods:
      - GET
      - POST
      - PUT
      - DELETE
      - OPTIONS
    allow_headers:
      - "*"
    expose_headers:
      - Content-Length
    allow_credentials: true
    max_age: 12h
    
  # 限流配置
  rate_limit:
    enabled: true
    requests_per_minute: 60
    burst: 10
    
  # 鉴权配置
  auth:
    enabled: true
    jwt_secret: "" # 通过环境变量 JWT_SECRET 设置
    token_expire: 24h

business:
  # 会话配置
  session:
    max_messages: 10 # 保留最近N轮对话
    default_style: xiaohongshu # xiaohongshu/dongyuhui
    
  # 商品推荐配置
  product:
    top_k: 10
    enable_cache: true
    
  # 重试配置
  retry:
    max_attempts: 3
    initial_delay: 100ms
    max_delay: 2s
    multiplier: 2

